version: "3"

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - "./qdrant_storage:/qdrant/storage:z"
      
  rag:
    depends_on:
      - qdrant
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag
    ports:
      - "8501:8501"
    environment:
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
